### ISSUE TITLE
Четвёртый релиз

### ISSUE THREAD

**Issue by nvamelichev** [livace/rpn-calculator#13]
- [x] Сборка с помощью [GraalVM native-image](https://www.graalvm.org/reference-manual/native-image/) или [jlink](https://medium.com/azulsystems/using-jlink-to-build-java-runtimes-for-non-modular-applications-9568c5e70ef4).
Docker для быстро запускающейся и быстро завершающейся утилиты shell будет странным и медленным решением
- [x] Настроена система непрерывной интеграции, запускающая тесты через Maven/Gradle на каждый коммит в main и на каждый коммит в пул-реквестах. CI берите любую бесплатную и интегрирующуюся с GitHub'ом: GitHub Actions, Travis CI, &hellip;

**Comment by asokol123** [comment]
* Сделаны автоматические релизы `native binary` на каждый тег
* Сделана сборка `Docker`-контейнера, action нужно запускать вручную потому что нужно редко
